echo off
echo HCENTIVE_HOME=%HCENTIVE_HOME%
echo HCENTIVE_EE_BUILD_PROFILE=%HCENTIVE_EE_BUILD_PROFILE%
echo 

set CSCCOMMMON_BASE_PATH=C:\CSCommonDev

echo CSCCOMMMON_BASE_PATH=%CSCCOMMMON_BASE_PATH%
echo TOMCAT_HOME=%TOMCAT_HOME%

set CMD=cscinitenv.cmd
echo CMD=%CMD%
call %CMD%